# **Online or In-Store – Where should I shop?** 
## Introduction to Data Science – Project Proposal
### *Ming Waters* 



> Online shopping is becoming more and more popular.  In 2015, 48% of overall purchases, excluding groceries, were made online. While online purchasing provides a host of conveniences, does it come at a price?  Are online prices higher than prices for the same at the store?  Are shoppers paying for the convenience or are prices lower online and they benefitting from the massive ease of price comparison and multiple vendor options? [^1]

> Alberto Cavallo, co-founder of MIT’s Billion Price Project, developed a study to compare thousands of item prices on-line and in store across 10 countries.  Cavallo’s study, published in the American Economic Review, found prices across the items were identical between online and in-store 72% of time.2   His study used the data to look at overall prices and did not group the results by type of products.  My project will use a subset of his data, US comparison, to determine if there is a particular type of product, e.g., electronics or office products. [^2]



#### Project Goal and Benefit:

Project will utilize Cavallo’s price data to determine if there are significant price differences between in-store and online prices for items by category and if there is are any significant differences in prices when the item is on sale.  This analysis will benefit many shoppers streamline their choices as they shop for items by category.

#### Data Set:  

My project will wrangle and analyze a small subset of Cavallo’s multi-country data. I will focus on the US price comparisons only comparing the in store prices with the Amazon price.  

Raw Data file was downloaded from: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi%3A10.7910%2FDVN%2FXXOUHF

#### Data Wrangling:

Initial analysis of the raw data shows the variables and observation in the format needed to manage with R, variables are in columns.  The table, however, needs to be cleaned and various data entry errors need to be managed before I can perform statistical analysis and visualization. 

Inspection of the data shows significant random typo errors.  Pricing on-line
or in-store have unusual values that do not match the items; making it clear that
the items were not entered correctly.

Significant data wrangling to remove these errors and outliers will have to take
place prior to any analysis.  

I had intended to use the sample data set to make overall predictions on the total
data but after wrangling the data I found that the sampling by category did not 
capture a broad distribution of prices per category.  There was not a good distribution of low, med, and high prices and often the entries were comparing 
prices for the same item repeatably.  The data was also riddled with multiple data entry and data gathering errors and I did not have full confidence based on my IQR method that the removal of all errors were performed.  

I can however, use this project to test my ability to wrangle a medium size data set
and perform multiple iterative outlier removal.  The final analysis will summarize
the findings and perhaps be useful for guiding the users to make some wise purchase decisions.

For my final submission, I plan to submit my code and final presentation deck outlining my approach and the relevant graphs used for data exploration and wrangling.



#### Analysis:

Data will be used to determine if there is a significant price difference between on-line and in store prices by category and if one particular category shows more observations of price benefits by source.  

Once the data is cleaned and I can visualize the delta by item and category, I will have a better handle on what type of statistical analysis will determine if there is significant difference shopping on line versus in store.  

***
[^1]: Anderson, George.  “Many shoppers are buying more online than in stores.”, Retail Wire, February 8, 2017 Web - http://www.retailwire.com/discussion/many-shoppers-are-buying-more-online-than-in-stores/ 

[^2]: Cavallo, Alberto, 2016, “Are-Online and Offline Prices Similar? Evidence from Large Multi-Channel Retailers”- American Economic Review doi:10.7910/DVN/XXOUHF, Harvard Dataverse, V4 






 


  




